# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf910c1665cd705b068ebac7863b1966"
name = "Amend"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  # Mandatory GDPR compliance webhooks (public apps).
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  # Handled by: /app/routes/webhooks.customers.data_request.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  # Handled by: /app/routes/webhooks.customers.redact.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  # Handled by: /app/routes/webhooks.shop.redact.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
